---
name: teamspeak
director_uuid: #Director UUID
jobs:
- instances: 1
  name: teamspeak
  networks:
  - name: default
    static_ips: [ 10.85.1.2 ] #IP of teamspeak server
  resource_pool: teamspeak_pool
  templates:
  - release: teamspeak
    name: teamspeak
releases:
- name: teamspeak
  version: latest
resource_pools:
- cloud_properties:
    ram: 2048
    disk: 20480
    cpu: 1
  name: teamspeak_pool
  network: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000 - 600000
  max_in_flight: 20
  serial: false
  update_watch_time: 30000 - 600000
properties:
  teamspeak_admin_token: #Admin token 
